version: 1.0
runtime:
  php_version: 8.2
  nodejs_version: 18
build:
  commands:
    - composer install --no-dev --optimize-autoloader
    - npm ci
    - npm run build
post-deployment:
  commands:
    - mkdir -p storage/framework/{sessions,views,cache}
    - chmod -R 775 storage bootstrap/cache