version: 1
build:
  - name: Install dependencies
    command: composer install --no-dev --optimize-autoloader
  - name: Generate application key
    command: php artisan key:generate
  - name: Optimize Laravel
    command: php artisan optimize
  - name: Build assets
    command: npm install && npm run build
deploy:
  - name: Deploy to production
    command: |
      php artisan storage:link
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache